name: Build Android

on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v4

      - name: Build
        run: |
             chmod +x ./build.sh
             ./build.sh

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: libOSMesa_${{matrix.arch}}
          path: /tmp/mesa/lib/libOSMesa_8.so
