name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-22.04

    steps:        
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
             sudo apt update
             sudo apt-get install -y libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev spirv-Headers glslang-tools
             pip3 install mako meson ninja

      - name: Build
        run: |
             export BUILD_ARCH=${{matrix.arch}}
             chmod +x ./build.bash
             ./build.bash

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: libOSMesa_${{matrix.arch}}
          path: /tmp/mesa/lib/libOSMesa_8.so
